---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-system
  namespace: flux-system
spec:
  eventSeverity: info
  summary: "flux cd notifications"
  eventMetadata:
    env: "staging"
    cluster: "notification-cluster"
  eventSources:
  - kind: Kustomization
    name: '*'
  - kind: HelmRelease
    name: '*'
  - kind: GitRepository
    name: '*'
  providerRef:
    name: slack
