---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  address: https://hooks.slack.com/services/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
  channel: flux-cd-notifications
  secretRef:
    name: slack-secret
  type: slack
