---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  address: https://hooks.slack.com/services/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
  channel: flux-cd-notifications
  secretRef:
    name: slack-secret
  type: slack
