apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-13
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3  # Number of Nginx pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: wordpress:latest
        ports:
        - containerPort: 80  # Expose port 80 inside the container

